name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build monitor image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.monitor
        push: false
        tags: nuki-monitor:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build web image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.web
        push: false
        tags: nuki-web:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
