name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-web.txt ]; then pip install -r requirements-web.txt; fi
    
    - name: Create example config files
      run: |
        mkdir -p config
        cp config/config.ini.example config/config.ini
        cp config/credentials.ini.example config/credentials.ini
    
    - name: Run sanitization check
      run: |
        python sanitize_check.py
    
    - name: Check code format with black
      run: |
        pip install black
        black --check .
    
    - name: Check for security issues with bandit
      run: |
        pip install bandit
        bandit -r . -x ./venv,./tests
